### PR TITLE
Create analytics tab

### PR DESCRIPTION
**Pull request by szekelyzol**
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207824756528855).

**Summary**

Based on internal feedback, I separated the Delivery and Analytics content in the documentation into 2 separate tabs. Details:

* added new product card for `Analytics & data` on main landing page
* updated internal linking for all delivery and analytics pages
* set up 301 redirects to map new paths
* renamed Delivery tab to `Delivery & players`
* added information about data retention for the total play endpoints
* removed Analytics content from the Delivery quickstart
* temporarily removed the Analytics quickstart page (which is a new page, so no redirect is needed as it has no incoming links yet)

⚠️ The Analytics quickstart page will be re-added to the documentation once all SDK readmes for our API clients are updated to show the new Analytics endpoints. Currently they still refer to the 2 "light analytics" endpoints. Example [here](https://docs.api.video/sdks/api-clients/apivideo-nodejs-client#analyticsapi).

### CODE REVIEW

**Comment by szekelyzol** [comment]
Preview build: https://api-video.doctave.dev/_preview/6963/

@S3b0u I added you as a reviewer because this change affects our sitemap and internal linking. And also becaue you give really good reviews 😅

**Comment by S3b0u** [comment]
@szekelyzol I checked the redirects, all good! ✅ 

But out of the new URLs, we have some odd ones:
- https://api-video.doctave.dev/_preview/6963/analytics/analytics
- https://api-video.doctave.dev/_preview/6963/delivery/delivery-quickstart

Both of them have a repetition of words, which is not ideal. I guess it's to avoid having multiple pages with the same slug.
So I would still recommend to edit the URLs listed above to something like this:
- https://api-video.doctave.dev/_preview/6963/analytics/overview
- https://api-video.doctave.dev/_preview/6963/delivery/quickstart
or
- https://api-video.doctave.dev/_preview/6963/analytics/quickstart
- https://api-video.doctave.dev/_preview/6963/delivery/quickstart
(in order to have some consistency accross the tabs)

Is that doable?

**Comment by szekelyzol** [comment]
> to edit the URLs listed above to something like this:
> 
> * https://api-video.doctave.dev/_preview/6963/analytics/overview
> * https://api-video.doctave.dev/_preview/6963/delivery/quickstart
>
>   (in order to have some consistency accross the tabs)
> 
> Is that doable?

Yes, it is definitely doable :) I'll go with ☝️ this version, because there will be a new Analytics quickstart page added later.

**Review by GuillaumeDGBN — APPROVED** [review]

**Review by S3b0u — APPROVED** [review]
Thank you for the latest changes, all good on my side!

**Pull request merged**
